apiVersion: s3.aws.m.upbound.io/v1beta1
kind: BucketWebsiteConfiguration
metadata:
  name: testy-test-test
  namespace: apps-testy-test-test
spec:
  forProvider:
    region: eu-west-2
    bucketRef:
      name: testy-test-test
    indexDocument:
      suffix: index.html
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
