apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bucket.yaml
  - bucket-public-access-block.yaml
  - bucket-policy.yaml
  - bucket-website-configuration.yaml
