apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-website
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chrispsheehan/backstage-sandbox.git
    targetRevision: main
    path: apps/${{ values.name }}/crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: apps-${{ values.name }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
