apiVersion: s3.aws.m.upbound.io/v1beta1
kind: BucketWebsiteConfiguration
metadata:
  name: uyvuyvuyvuyvuv
  namespace: apps-uyvuyvuyvuyvuv
  annotations:
    crossplane.io/poll-interval: "5m"
spec:
  forProvider:
    region: eu-west-2
    bucketRef:
      name: uyvuyvuyvuyvuv
    indexDocument:
      suffix: index.html
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
