apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  BACKEND_SECRET: local-dev-backend-secret
  AUTH_GITHUB_CLIENT_ID: local-dev-client-id
  AUTH_GITHUB_CLIENT_SECRET: local-dev-client-secret
