apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backstage

images:
  - name: backstage-lab
    newName: 700060376888.dkr.ecr.eu-west-2.amazonaws.com/backstage-sandbox-dev
    newTag: fc822450d0bb0130245dba60d9db1936cf8fa168

patches:
  - path: serviceaccount-image-pull-secret.yaml
