apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backstage

images:
  - name: backstage-lab
    newName: 700060376888.dkr.ecr.eu-west-2.amazonaws.com/backstage-sandbox-dev
    newTag: df5051e26fe8419162358832973603af74cf3b88

patches:
  - path: serviceaccount-image-pull-secret.yaml
  - path: service-nodeport.yaml
  - path: external-url.yaml
