apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/backstage

images:
  - name: backstage-lab
    newName: 700060376888.dkr.ecr.eu-west-2.amazonaws.com/backstage-sandbox-dev
    newTag: 04b44d9b7868771a7926e18967582cf5e775a20f

patches:
  - path: serviceaccount-image-pull-secret.yaml
