apiVersion: s3.aws.m.upbound.io/v1beta1
kind: BucketPolicy
metadata:
  name: test-this
  namespace: apps-test-this
  annotations:
    crossplane.io/poll-interval: "5m"
spec:
  forProvider:
    region: eu-west-2
    bucketRef:
      name: test-this
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "PublicReadForWebsite",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::test-this-700060376888-eu-west-2/*"
          }
        ]
      }
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig
